- name: Install Apache in Ubuntu servers
  hosts: datacenter
  become: true

  vars:
    http_port: 80
    http_host: JLR
    http_conf: jlr.conf

  tasks:

    - name: install apache2 package
      ansible.builtin.apt:
        name: apache2
        update_cache: true
        state: latest

    - name: "create /var/www/{{ http_host }}/ directory"
      ansible.builtin.file:
        path: "/var/www/{{ http_host }}"
        state: directory
        mode: '0777'

    - name: Copy your index file
      ansible.builtin.template:
        src: "templates/index-template.html"
        dest: "/var/www/{{ http_host }}/index.html"

    - name: Set up virtuahHost
      ansible.builtin.template:
        src: "templates/apache-template.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"

    - name: Enable site
      command: "a2ensite {{ http_conf }}"

    - name: Enable site
      command: a2dissite 000-default.conf
      notify: restart-apache
 
  handlers:

    - name: restart-apache
      ansible.builtin.service:
        name: apache2
        state: restarted
