- name: Demostrate idempotency
  hosts: ubuntu-3
  become: true

  tasks:

    - name: "FIRST TASKT: Create /tmp/idempotency-example directory"
      ansible.builtin.file:
        path: "Create /tmp/idempotency-example directory"
        state: directory
        mode: '0777'

    - name: "SECOND TASK: Create /tmp/idempotency-example directory"
      ansible.builtin.file:
        path: "Create /tmp/idempotency-example directory"
        state: directory
        mode: '0777'
