- hosts: datacenter
  become: true

  vars:
    http_port: 80
    http_host: whatever

  tasks:

    - name: stop apache
      ansible.builtin.service:
        name: apache2
        enabled: false
        state: stopped

    - name: delete /var/www/demo/index.html file
      ansible.builtin.file:
        path: /var/www/demo/index.html
        state: absent

    - name: delete /var/www/demo/ directory
      ansible.builtin.file:
        path: /var/www/demo
        state: absent

    - name: delete /etc/apache2/sites-available/demo.conf
      ansible.builtin.file:
        path: /etc/apache2/sites-available/demo.conf
        state: absent

    - name: uninstall apache2 package
      ansible.builtin.apt:
        name: apache2
        state: absent

#    - name: UFW firewall allow HTTP on port 80
#      community.general.ufw:
#        rule: allow
#        port: 80
#        proto: tcp
