- name: Delete config and uninstall Apache2 in Ubuntu servers
  hosts: datacenter
  become: true

  vars:
    http_port: 80
    http_host: JLR
    http_conf: jlr.conf

  tasks:

    - name: stop apache
      ansible.builtin.service:
        name: apache2
        enabled: false
        state: stopped

    - name: "delete /var/www/{{ http_host }}/index.html file"
      ansible.builtin.file:
        path: "/var/www/{{ http_host }}/index.html"
        state: absent

    - name: "delete /var/www/{{ http_host }}/ directory"
      ansible.builtin.file:
        path: "/var/www/{{ http_host }}"
        state: absent

    - name: "delete /etc/apache2/sites-available/{{ http_conf }}"
      ansible.builtin.file:
        path: "/etc/apache2/sites-available/{{ http_conf }}"
        state: absent

    - name: uninstall apache2 package
      ansible.builtin.apt:
        name: apache2
        state: absent
